export const LOGIN = 'LOGIN';
export const SET_HOSTNAME = 'SET_HOSTNAME';

export const GET_SECTORS = 'GET_SECTORS';
export const GET_TABLES = 'GET_TABLES';
export const SET_TABLE = 'SET_TABLE';
export const GET_TABLE = 'GET_TABLE';
export const TAKE_TABLE = 'TAKE_TABLE';
export const FREE_TABLE = 'FREE_TABLE';

export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_ORDER = 'GET_ORDER';
export const HAVE_ORDER = 'HAVE_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const CHANGE_ORDER_STATE = 'CHANGE_ORDER_STATE';
export const CLOSE_ORDER = 'CLOSE_ORDER';
export const SEND_ORDERLINES = 'SEND_ORDERLINES';
export const ADD_ORDERLINE = 'ADD_ORDERLINE';
export const EDIT_ORDERLINE = 'EDIT_ORDERLINE';
export const POST_ORDERLINES = 'POST_ORDERLINES';

export const ADD_ORDERLINE_PROMO = 'ADD_ORDERLINE_PROMO';
export const DELETE_ORDERLINE_PROMO = 'DELETE_ORDERLINE_PROMO';
export const CHANGE_STATUS_ORDERLINE_PROMO = 'CHANGE_STATUS_ORDERLINE_PROMO';

export const ADD_ORDERLINE_PRODUCT = 'ADD_ORDERLINE_PRODUCT';
export const DELETE_ORDERLINE_PRODUCT = 'DELETE_ORDERLINE_PRODUCT';
export const CHANGE_STATUS_ORDERLINE_PRODUCT = 'CHANGE_STATUS_ORDERLINE_PRODUCT';

export const ADD_ORDERLINE_DISH = 'ADD_ORDERLINE_DISH';
export const DELETE_ORDERLINE_DISH = 'DELETE_ORDERLINE_DISH';
export const CHANGE_STATUS_ORDERLINE_DISH = 'CHANGE_STATUS_ORDERLINE_DISH';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_DISHES = 'GET_DISHES';
export const GET_DISH = 'GET_DISH';
export const FILTER_DISHES = 'FILTER_DISHES';
export const SET_DISH = 'SET_DISH';
export const ADD_DISH = 'ADD_DISH';
export const EDIT_DISH = 'EDIT_DISH';
export const DELETE_DISH = 'DELETE_DISH';

export const GET_PROMOS = 'GET_PROMOS';
export const GET_PROMO = 'GET_PROMO';
export const FILTER_PROMOS = 'FILTER_PROMOS';
export const SET_PROMO = 'SET_PROMO';
export const ADD_PROMO = 'ADD_PROMO';
export const EDIT_PROMO = 'EDIT_PROMO';
export const DELETE_PROMO = 'DELETE_PROMO';

export const GET_COMMANDS = 'GET_COMMANDS';
export const ADD_COMMAND = 'ADD_COMMAND';
export const ADD_COMMANDS = 'ADD_COMMANDS';
export const DELETE_COMMAND = 'DELETE_COMMAND';
export const DELETE_COMMANDS = 'DELETE_COMMANDS';

export const GET_TIMEZONES = 'GET_TIMEZONES';
export const GET_TIMEZONE = 'GET_TIMEZONE';
export const ADD_TIMEZONE = 'ADD_TIMEZONE';
export const EDIT_TIMEZONE = 'EDIT_TIMEZONE';
export const DELETE_TIMEZONE = 'DELETE_TIMEZONE';

export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const GET_RESERVATION = 'GET_RESERVATION';
export const GET_RESERVATION_TABLES = 'GET_RESERVATION_TABLES';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const EDIT_RESERVATION = 'EDIT_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKET = 'GET_TICKET';
export const PAY_TICKET = 'PAY_TICKET';

export const GET_PAYMENT_TYPES = 'GET_PAYMENT_TYPES';
export const GET_PAYMENTS = 'GET_PAYMENTS';
